# Generated by Django 5.1.2 on 2024-11-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_joindes',
            new_name='date_of_joined',
        ),
        migrations.AddField(
            model_name='property',
            name='p_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
